services:
  dev-db:
    image: postgres:13-alpine
    container_name: tutorial-db
    volumes:
      - tutorial-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
volumes:
  tutorial-db:
